#############################################################################
# Makefile for building: Proyecto_FInal
# Generated by qmake (2.01a) (Qt 4.8.7) on: mié may 15 10:34:20 2019
# Project:  Proyecto_FInal.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Proyecto_FInal.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		item_grafico.cpp \
		movimiento.cpp \
		objeto_mov.cpp \
		nombre_partida.cpp \
		escena.cpp \
		control_usuario.cpp \
		database.cpp \
		menu.cpp moc_mainwindow.cpp \
		moc_objeto_mov.cpp \
		moc_nombre_partida.cpp \
		moc_control_usuario.cpp \
		moc_menu.cpp \
		qrc_imagenes.cpp
OBJECTS       = main.o \
		mainwindow.o \
		item_grafico.o \
		movimiento.o \
		objeto_mov.o \
		nombre_partida.o \
		escena.o \
		control_usuario.o \
		database.o \
		menu.o \
		moc_mainwindow.o \
		moc_objeto_mov.o \
		moc_nombre_partida.o \
		moc_control_usuario.o \
		moc_menu.o \
		qrc_imagenes.o
DIST          = imagenes/fondo.png \
		imagenes/Bala1.png \
		imagenes/Bala2.png \
		imagenes/bullet.png \
		imagenes/cancel.png \
		imagenes/dificult.png \
		imagenes/done.png \
		imagenes/exit.png \
		imagenes/fondo.png \
		imagenes/intro.png \
		imagenes/life.png \
		imagenes/Load.png \
		imagenes/mario.png \
		imagenes/mira.png \
		imagenes/mira1.png \
		imagenes/new.png \
		imagenes/nickgame.png \
		imagenes/nickname.png \
		imagenes/password.png \
		imagenes/pollo.png \
		imagenes/pollo2.png \
		imagenes/score.png \
		imagenes/user.png \
		imagenes/senor1.png \
		imagenes/nick.png \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Proyecto_FInal.pro
QMAKE_TARGET  = Proyecto_FInal
DESTDIR       = 
TARGET        = Proyecto_FInal

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_nombre_partida.h ui_control_usuario.h ui_menu.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Proyecto_FInal.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile Proyecto_FInal.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile Proyecto_FInal.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Proyecto_FInal1.0.0 || $(MKDIR) .tmp/Proyecto_FInal1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Proyecto_FInal1.0.0/ && $(COPY_FILE) --parents mainwindow.h item_grafico.h movimiento.h objeto_mov.h nombre_partida.h escena.h control_usuario.h database.h menu.h .tmp/Proyecto_FInal1.0.0/ && $(COPY_FILE) --parents imagenes.qrc .tmp/Proyecto_FInal1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp item_grafico.cpp movimiento.cpp objeto_mov.cpp nombre_partida.cpp escena.cpp control_usuario.cpp database.cpp menu.cpp .tmp/Proyecto_FInal1.0.0/ && $(COPY_FILE) --parents mainwindow.ui nombre_partida.ui control_usuario.ui menu.ui .tmp/Proyecto_FInal1.0.0/ && (cd `dirname .tmp/Proyecto_FInal1.0.0` && $(TAR) Proyecto_FInal1.0.0.tar Proyecto_FInal1.0.0 && $(COMPRESS) Proyecto_FInal1.0.0.tar) && $(MOVE) `dirname .tmp/Proyecto_FInal1.0.0`/Proyecto_FInal1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Proyecto_FInal1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_objeto_mov.cpp moc_nombre_partida.cpp moc_control_usuario.cpp moc_menu.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_objeto_mov.cpp moc_nombre_partida.cpp moc_control_usuario.cpp moc_menu.cpp
moc_mainwindow.cpp: item_grafico.h \
		objeto_mov.h \
		movimiento.h \
		escena.h \
		database.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_objeto_mov.cpp: movimiento.h \
		objeto_mov.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) objeto_mov.h -o moc_objeto_mov.cpp

moc_nombre_partida.cpp: nombre_partida.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) nombre_partida.h -o moc_nombre_partida.cpp

moc_control_usuario.cpp: database.h \
		menu.h \
		mainwindow.h \
		item_grafico.h \
		objeto_mov.h \
		movimiento.h \
		escena.h \
		control_usuario.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) control_usuario.h -o moc_control_usuario.cpp

moc_menu.cpp: database.h \
		mainwindow.h \
		item_grafico.h \
		objeto_mov.h \
		movimiento.h \
		escena.h \
		menu.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) menu.h -o moc_menu.cpp

compiler_rcc_make_all: qrc_imagenes.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_imagenes.cpp
qrc_imagenes.cpp: imagenes.qrc
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name imagenes imagenes.qrc -o qrc_imagenes.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_nombre_partida.h ui_control_usuario.h ui_menu.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_nombre_partida.h ui_control_usuario.h ui_menu.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_nombre_partida.h: nombre_partida.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic nombre_partida.ui -o ui_nombre_partida.h

ui_control_usuario.h: control_usuario.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic control_usuario.ui -o ui_control_usuario.h

ui_menu.h: menu.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic menu.ui -o ui_menu.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp control_usuario.h \
		database.h \
		menu.h \
		mainwindow.h \
		item_grafico.h \
		objeto_mov.h \
		movimiento.h \
		escena.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		item_grafico.h \
		objeto_mov.h \
		movimiento.h \
		escena.h \
		database.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

item_grafico.o: item_grafico.cpp item_grafico.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item_grafico.o item_grafico.cpp

movimiento.o: movimiento.cpp movimiento.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movimiento.o movimiento.cpp

objeto_mov.o: objeto_mov.cpp objeto_mov.h \
		movimiento.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objeto_mov.o objeto_mov.cpp

nombre_partida.o: nombre_partida.cpp nombre_partida.h \
		ui_nombre_partida.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nombre_partida.o nombre_partida.cpp

escena.o: escena.cpp escena.h \
		item_grafico.h \
		objeto_mov.h \
		movimiento.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o escena.o escena.cpp

control_usuario.o: control_usuario.cpp control_usuario.h \
		database.h \
		menu.h \
		mainwindow.h \
		item_grafico.h \
		objeto_mov.h \
		movimiento.h \
		escena.h \
		ui_control_usuario.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o control_usuario.o control_usuario.cpp

database.o: database.cpp database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

menu.o: menu.cpp menu.h \
		database.h \
		mainwindow.h \
		item_grafico.h \
		objeto_mov.h \
		movimiento.h \
		escena.h \
		ui_menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menu.o menu.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_objeto_mov.o: moc_objeto_mov.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_objeto_mov.o moc_objeto_mov.cpp

moc_nombre_partida.o: moc_nombre_partida.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nombre_partida.o moc_nombre_partida.cpp

moc_control_usuario.o: moc_control_usuario.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_control_usuario.o moc_control_usuario.cpp

moc_menu.o: moc_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menu.o moc_menu.cpp

qrc_imagenes.o: qrc_imagenes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_imagenes.o qrc_imagenes.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/Proyecto_FInal/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/Proyecto_FInal/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/Proyecto_FInal/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/Proyecto_FInal/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/Proyecto_FInal/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Proyecto_FInal/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

